name: CI Pipline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs: 
  lab3_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test_1
        run: flake8 .
      - name: Test_2
        run: pytest
      - name: Test_3
        run: bandit -r . --skip B101
        
  lab3_job3:
    runs-on: ubuntu-latest
    needs: [lab3_job1]
    if: always()
    steps:
      - name: Отправка боту в случае успеха
        if: ${{ needs.lab3_job1.result == 'success' }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Успешный запуск Pipeline"
      - name: Отправка боту в случае провала
        if: ${{ needs.lab3_job1.result != 'success' }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Запуск Pipeline сопровожден ошибкой"

